import { useState, useCallback, useEffect } from 'react'
import type { Conversation, Message, GenerativeUIBlock, ToolCallBlock } from '../types'
import { getConversationAccent } from '../lib/theme'

function uid() {
  return Math.random().toString(36).slice(2) + Date.now().toString(36)
}

function makeConversation(title = 'New conversation'): Conversation {
  const id = uid()
  return {
    id,
    title,
    accentColor: getConversationAccent(id),
    messages: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
}

/* ── Demo conversation showcasing generative UI ─────────── */
const demoConv = makeConversation('UI on the Fly — Demo')

const DEMO_MESSAGES: Message[] = [
  {
    id: uid(),
    role: 'user',
    content: 'Give me a warm earth-tone color palette',
    status: 'done',
    createdAt: Date.now() - 120_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is a warm earth-tone palette — click any swatch to copy the hex.',
    status: 'done',
    createdAt: Date.now() - 118_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'widget',
        widgetType: 'ColorPalette',
        caption: 'Warm earth tones',
        props: {
          colors: [
            { name: 'Sand',     hex: '#C8A97E', role: 'background' },
            { name: 'Terracotta', hex: '#C1674A', role: 'primary' },
            { name: 'Sienna',   hex: '#8B4513', role: 'accent' },
            { name: 'Olive',    hex: '#6B6B3A', role: 'secondary' },
            { name: 'Cream',    hex: '#F5ECD7', role: 'surface' },
            { name: 'Charcoal', hex: '#2C2416', role: 'text' },
          ],
        },
      } satisfies GenerativeUIBlock,
    ],
  },
  {
    id: uid(),
    role: 'user',
    content: 'Pros and cons of TypeScript?',
    status: 'done',
    createdAt: Date.now() - 90_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is a structured breakdown:',
    status: 'done',
    createdAt: Date.now() - 88_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'widget',
        widgetType: 'ProsConsList',
        props: {
          topic: 'TypeScript',
          pros: ['Static typing catches bugs early', 'Great IDE autocomplete', 'Self-documenting code', 'Scales well in large teams'],
          cons: ['Adds build step complexity', 'Verbose for small scripts', 'Type gymnastics for advanced cases', 'Slower initial setup'],
        },
      } satisfies GenerativeUIBlock,
    ],
  },
  {
    id: uid(),
    role: 'user',
    content: 'Build me a live BMI calculator',
    status: 'done',
    createdAt: Date.now() - 60_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is an interactive BMI calculator — AI-generated, running live in a sandbox:',
    status: 'done',
    createdAt: Date.now() - 58_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'generated',
        caption: 'BMI Calculator — generated by AI',
        code: `
function BMICalc() {
  const [height, setHeight] = useState('');
  const [weight, setWeight] = useState('');
  const bmi = height && weight ? (parseFloat(weight) / Math.pow(parseFloat(height) / 100, 2)).toFixed(1) : null;
  const category = bmi === null ? null :
    bmi < 18.5 ? { label: 'UNDERWEIGHT', color: ds.colors.blue } :
    bmi < 25   ? { label: 'HEALTHY',     color: ds.colors.green } :
    bmi < 30   ? { label: 'OVERWEIGHT',  color: ds.colors.yellow } :
                 { label: 'OBESE',       color: ds.colors.red };

  const inputStyle = {
    width: '100%', padding: '8px 10px',
    border: '2px solid #000', background: '#fff',
    fontFamily: ds.fonts.mono, fontSize: 14, color: '#000',
    outline: 'none', boxSizing: 'border-box',
  };
  const labelStyle = { ...ds.stamp, display: 'block', marginBottom: 4 };

  return (
    <div style={{ padding: 20, background: '#FFFCF0', fontFamily: ds.fonts.mono }}>
      <div style={{ ...ds.heading(28), marginBottom: 16 }}>BMI CALCULATOR</div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
        <div>
          <label style={labelStyle}>HEIGHT (cm)</label>
          <input style={inputStyle} type="number" placeholder="e.g. 175"
            value={height} onChange={e => setHeight(e.target.value)} />
        </div>
        <div>
          <label style={labelStyle}>WEIGHT (kg)</label>
          <input style={inputStyle} type="number" placeholder="e.g. 70"
            value={weight} onChange={e => setWeight(e.target.value)} />
        </div>
      </div>
      {category && (
        <div style={{ border: '2px solid #000', boxShadow: ds.shadows.md, overflow: 'hidden' }}>
          <div style={{ background: category.color, borderBottom: '2px solid #000', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={ds.heading(22)}>{category.label}</span>
            <span style={{ fontFamily: ds.fonts.display, fontSize: 32 }}>{bmi}</span>
          </div>
          <div style={{ background: '#fff', padding: '8px 14px', display: 'flex', gap: 16 }}>
            {[['< 18.5','Underweight',ds.colors.blue],['18.5–24.9','Healthy',ds.colors.green],['25–29.9','Overweight',ds.colors.yellow],['>= 30','Obese',ds.colors.red]].map(([range,label,color])=>(
              <div key={label} style={{ flex: 1, borderLeft: \`3px solid \${color}\`, paddingLeft: 6 }}>
                <div style={{ fontSize: 9, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#555' }}>{label}</div>
                <div style={{ fontSize: 11, fontWeight: 500 }}>{range}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
render(<BMICalc />);
`,
      } satisfies GenerativeUIBlock,
    ],
  },
]

demoConv.messages = DEMO_MESSAGES
demoConv.updatedAt = Date.now() - 50_000
demoConv.title = 'UI on the Fly — Demo'

/* ── Tool call demo ─────────────────────────────────────── */
const toolDemoConv = makeConversation('Web Search — Demo')

const TOOL_DEMO_MESSAGES: Message[] = [
  {
    id: uid(),
    role: 'user',
    content: 'What are the latest developments in quantum computing?',
    status: 'done',
    createdAt: Date.now() - 45_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content:
      'Based on my web search, here are the latest developments in quantum computing:\n\n' +
      '**IBM** recently announced their 1,121-qubit Condor processor, making it the largest quantum processor to date. ' +
      'Meanwhile, **Google** has demonstrated quantum error correction at scale with their new Willow chip.\n\n' +
      '**Microsoft** is investing heavily in topological qubits, which promise more stable quantum states. ' +
      'And **IonQ** has achieved record-breaking gate fidelities with their trapped-ion approach.\n\n' +
      'The field is progressing rapidly toward practical quantum advantage in areas like drug discovery, ' +
      'cryptography, and materials science.',
    status: 'done',
    createdAt: Date.now() - 43_000,
    blocks: [
      {
        type: 'tool_call',
        id: 'toolu_demo_1',
        toolName: 'web_search',
        args: { query: 'latest quantum computing developments 2025' },
        status: 'success',
        durationMs: 1340,
        result: {
          query: 'latest quantum computing developments 2025',
          count: 5,
          results: [
            {
              title: 'IBM Unveils 1,121-Qubit Condor Quantum Processor',
              url: 'https://research.ibm.com/blog/quantum-condor',
              snippet:
                'IBM has announced Condor, its largest quantum processor to date with 1,121 qubits, marking a significant milestone in quantum computing hardware.',
            },
            {
              title: "Google's Willow Chip Achieves Quantum Error Correction Breakthrough",
              url: 'https://blog.google/technology/research/quantum-willow-chip/',
              snippet:
                "Google's new Willow quantum chip demonstrates below-threshold quantum error correction, a key milestone toward practical quantum computing.",
            },
            {
              title: 'Microsoft Advances Topological Qubit Research',
              url: 'https://azure.microsoft.com/en-us/blog/quantum-topological/',
              snippet:
                "Microsoft's approach to topological qubits shows promise for more stable quantum states, potentially reducing error rates by orders of magnitude.",
            },
            {
              title: 'IonQ Achieves Record Gate Fidelities',
              url: 'https://ionq.com/news/gate-fidelity-record',
              snippet:
                'IonQ has set new records for quantum gate fidelities using trapped-ion technology, achieving 99.9% two-qubit gate fidelity.',
            },
            {
              title: 'Quantum Computing Market to Reach $65B by 2030',
              url: 'https://www.mckinsey.com/quantum-computing-market',
              snippet:
                'McKinsey projects the quantum computing market will grow to $65 billion by 2030, driven by advances in hardware and increasing enterprise adoption.',
            },
          ],
        },
      } satisfies ToolCallBlock,
    ],
  },
]

toolDemoConv.messages = TOOL_DEMO_MESSAGES
toolDemoConv.updatedAt = Date.now() - 40_000
toolDemoConv.title = 'Web Search — Demo'

/* ── Artifact demo ──────────────────────────────────────── */
const artifactDemoConv = makeConversation('Artifact Demo')

const ARTIFACT_CODE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'DM Mono', monospace; background: #FFFCF0; padding: 24px; }
    h1 { font-family: 'Bebas Neue', sans-serif; font-size: 48px; letter-spacing: 0.04em; margin-bottom: 16px; }
    .card { background: #fff; border: 2px solid #000; box-shadow: 3px 3px 0 #000; padding: 16px; margin-bottom: 12px; }
    .card:hover { transform: translate(-2px, -2px); box-shadow: 5px 5px 0 #000; transition: all 0.1s; }
    .btn { background: #FFE500; border: 2px solid #000; box-shadow: 2px 2px 0 #000; padding: 8px 16px; font-family: 'DM Mono', monospace; font-size: 13px; cursor: pointer; }
    .btn:active { transform: translate(2px, 2px); box-shadow: none; }
    .counter { font-size: 64px; font-family: 'Bebas Neue', sans-serif; text-align: center; padding: 24px; }
  </style>
</head>
<body>
  <h1>BRUTALIST COUNTER</h1>
  <div class="card">
    <div class="counter" id="count">0</div>
  </div>
  <div style="display: flex; gap: 8px;">
    <button class="btn" onclick="update(-1)">- MINUS</button>
    <button class="btn" onclick="update(1)">+ PLUS</button>
    <button class="btn" onclick="reset()" style="background: #FF3B3B; color: #fff;">RESET</button>
  </div>
  <script>
    let count = 0;
    const el = document.getElementById('count');
    function update(n) { count += n; el.textContent = count; console.log('Count:', count); }
    function reset() { count = 0; el.textContent = count; console.log('Reset!'); }
  </script>
</body>
</html>`

const ARTIFACT_DEMO_MESSAGES: Message[] = [
  {
    id: uid(),
    role: 'user',
    content: 'Build me a simple counter app in HTML',
    status: 'done',
    createdAt: Date.now() - 30_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is a brutalist counter app. Click the **OPEN** button on the code block to view it in the artifact panel with a live preview:\n\n```html\n' + ARTIFACT_CODE + '\n```\n\nThe counter features increment, decrement, and reset buttons with the neo-brutalist design system.',
    status: 'done',
    createdAt: Date.now() - 28_000,
  },
]

artifactDemoConv.messages = ARTIFACT_DEMO_MESSAGES
artifactDemoConv.updatedAt = Date.now() - 25_000
artifactDemoConv.title = 'Artifact Demo — Counter'

const SEED_CONVERSATIONS: Conversation[] = [
  artifactDemoConv,
  toolDemoConv,
  demoConv,
  { ...makeConversation('Build a landing page'), messages: [], updatedAt: Date.now() - 60_000 },
  { ...makeConversation('Explain quantum computing'), messages: [], updatedAt: Date.now() - 3_600_000 },
  { ...makeConversation('Refactor auth module'), messages: [], updatedAt: Date.now() - 86_400_000 },
]

const STORAGE_KEY_CONVERSATIONS = 'ink-ai-conversations'
const STORAGE_KEY_ACTIVE_ID = 'ink-ai-active-id'

function loadFromStorage<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key)
    if (raw === null) return fallback
    return JSON.parse(raw) as T
  } catch {
    return fallback
  }
}

export function useConversations() {
  const [conversations, setConversations] = useState<Conversation[]>(
    () => loadFromStorage(STORAGE_KEY_CONVERSATIONS, SEED_CONVERSATIONS)
  )
  const [activeId, setActiveId] = useState<string | null>(
    () => loadFromStorage(STORAGE_KEY_ACTIVE_ID, null)
  )

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY_CONVERSATIONS, JSON.stringify(conversations))
  }, [conversations])

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY_ACTIVE_ID, JSON.stringify(activeId))
  }, [activeId])

  const activeConversation = conversations.find((c) => c.id === activeId) ?? null

  const createConversation = useCallback(() => {
    const c = makeConversation()
    setConversations((prev) => [c, ...prev])
    setActiveId(c.id)
    return c
  }, [])

  const selectConversation = useCallback((id: string) => {
    setActiveId(id)
  }, [])

  const addMessage = useCallback((conversationId: string, message: Message) => {
    setConversations((prev) =>
      prev.map((c) =>
        c.id === conversationId
          ? {
              ...c,
              messages: [...c.messages, message],
              updatedAt: Date.now(),
              title: c.messages.length === 0 && message.role === 'user'
                ? message.content.slice(0, 48)
                : c.title,
            }
          : c
      )
    )
  }, [])

  const updateMessage = useCallback((conversationId: string, messageId: string, patch: Partial<Message>) => {
    setConversations((prev) =>
      prev.map((c) =>
        c.id === conversationId
          ? {
              ...c,
              messages: c.messages.map((m) =>
                m.id === messageId ? { ...m, ...patch } : m
              ),
            }
          : c
      )
    )
  }, [])

  const deleteConversation = useCallback((id: string) => {
    setConversations((prev) => prev.filter((c) => c.id !== id))
    setActiveId((prev) => (prev === id ? null : prev))
  }, [])

  /** Reset an AI message and remove all messages after it (for regeneration). */
  const resetMessage = useCallback((conversationId: string, messageId: string) => {
    setConversations((prev) =>
      prev.map((c) => {
        if (c.id !== conversationId) return c
        const idx = c.messages.findIndex((m) => m.id === messageId)
        if (idx < 0) return c
        const messages = c.messages.slice(0, idx + 1)
        messages[idx] = { ...messages[idx], content: '', blocks: [], status: 'pending' }
        return { ...c, messages }
      })
    )
  }, [])

  return {
    conversations,
    activeId,
    activeConversation,
    createConversation,
    selectConversation,
    addMessage,
    updateMessage,
    resetMessage,
    deleteConversation,
  }
}
