import { useState, useCallback } from 'react'
import type { Conversation, Message, GenerativeUIBlock } from '../types'
import { getConversationAccent } from '../lib/theme'

function uid() {
  return Math.random().toString(36).slice(2) + Date.now().toString(36)
}

function makeConversation(title = 'New conversation'): Conversation {
  const id = uid()
  return {
    id,
    title,
    accentColor: getConversationAccent(id),
    messages: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
}

/* ── Demo conversation showcasing generative UI ─────────── */
const demoConv = makeConversation('UI on the Fly — Demo')

const DEMO_MESSAGES: Message[] = [
  {
    id: uid(),
    role: 'user',
    content: 'Give me a warm earth-tone color palette',
    status: 'done',
    createdAt: Date.now() - 120_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is a warm earth-tone palette — click any swatch to copy the hex.',
    status: 'done',
    createdAt: Date.now() - 118_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'widget',
        widgetType: 'ColorPalette',
        caption: 'Warm earth tones',
        props: {
          colors: [
            { name: 'Sand',     hex: '#C8A97E', role: 'background' },
            { name: 'Terracotta', hex: '#C1674A', role: 'primary' },
            { name: 'Sienna',   hex: '#8B4513', role: 'accent' },
            { name: 'Olive',    hex: '#6B6B3A', role: 'secondary' },
            { name: 'Cream',    hex: '#F5ECD7', role: 'surface' },
            { name: 'Charcoal', hex: '#2C2416', role: 'text' },
          ],
        },
      } satisfies GenerativeUIBlock,
    ],
  },
  {
    id: uid(),
    role: 'user',
    content: 'Pros and cons of TypeScript?',
    status: 'done',
    createdAt: Date.now() - 90_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is a structured breakdown:',
    status: 'done',
    createdAt: Date.now() - 88_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'widget',
        widgetType: 'ProsConsList',
        props: {
          topic: 'TypeScript',
          pros: ['Static typing catches bugs early', 'Great IDE autocomplete', 'Self-documenting code', 'Scales well in large teams'],
          cons: ['Adds build step complexity', 'Verbose for small scripts', 'Type gymnastics for advanced cases', 'Slower initial setup'],
        },
      } satisfies GenerativeUIBlock,
    ],
  },
  {
    id: uid(),
    role: 'user',
    content: 'Build me a live BMI calculator',
    status: 'done',
    createdAt: Date.now() - 60_000,
  },
  {
    id: uid(),
    role: 'assistant',
    content: 'Here is an interactive BMI calculator — AI-generated, running live in a sandbox:',
    status: 'done',
    createdAt: Date.now() - 58_000,
    blocks: [
      {
        type: 'generative_ui',
        mode: 'generated',
        caption: 'BMI Calculator — generated by AI',
        code: `
function BMICalc() {
  const [height, setHeight] = useState('');
  const [weight, setWeight] = useState('');
  const bmi = height && weight ? (parseFloat(weight) / Math.pow(parseFloat(height) / 100, 2)).toFixed(1) : null;
  const category = bmi === null ? null :
    bmi < 18.5 ? { label: 'UNDERWEIGHT', color: ds.colors.blue } :
    bmi < 25   ? { label: 'HEALTHY',     color: ds.colors.green } :
    bmi < 30   ? { label: 'OVERWEIGHT',  color: ds.colors.yellow } :
                 { label: 'OBESE',       color: ds.colors.red };

  const inputStyle = {
    width: '100%', padding: '8px 10px',
    border: '2px solid #000', background: '#fff',
    fontFamily: ds.fonts.mono, fontSize: 14, color: '#000',
    outline: 'none', boxSizing: 'border-box',
  };
  const labelStyle = { ...ds.stamp, display: 'block', marginBottom: 4 };

  return (
    <div style={{ padding: 20, background: '#FFFCF0', fontFamily: ds.fonts.mono }}>
      <div style={{ ...ds.heading(28), marginBottom: 16 }}>BMI CALCULATOR</div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
        <div>
          <label style={labelStyle}>HEIGHT (cm)</label>
          <input style={inputStyle} type="number" placeholder="e.g. 175"
            value={height} onChange={e => setHeight(e.target.value)} />
        </div>
        <div>
          <label style={labelStyle}>WEIGHT (kg)</label>
          <input style={inputStyle} type="number" placeholder="e.g. 70"
            value={weight} onChange={e => setWeight(e.target.value)} />
        </div>
      </div>
      {category && (
        <div style={{ border: '2px solid #000', boxShadow: ds.shadows.md, overflow: 'hidden' }}>
          <div style={{ background: category.color, borderBottom: '2px solid #000', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={ds.heading(22)}>{category.label}</span>
            <span style={{ fontFamily: ds.fonts.display, fontSize: 32 }}>{bmi}</span>
          </div>
          <div style={{ background: '#fff', padding: '8px 14px', display: 'flex', gap: 16 }}>
            {[['< 18.5','Underweight',ds.colors.blue],['18.5–24.9','Healthy',ds.colors.green],['25–29.9','Overweight',ds.colors.yellow],['>= 30','Obese',ds.colors.red]].map(([range,label,color])=>(
              <div key={label} style={{ flex: 1, borderLeft: \`3px solid \${color}\`, paddingLeft: 6 }}>
                <div style={{ fontSize: 9, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#555' }}>{label}</div>
                <div style={{ fontSize: 11, fontWeight: 500 }}>{range}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
render(<BMICalc />);
`,
      } satisfies GenerativeUIBlock,
    ],
  },
]

demoConv.messages = DEMO_MESSAGES
demoConv.updatedAt = Date.now() - 50_000
demoConv.title = 'UI on the Fly — Demo'

const SEED_CONVERSATIONS: Conversation[] = [
  demoConv,
  { ...makeConversation('Build a landing page'), messages: [], updatedAt: Date.now() - 60_000 },
  { ...makeConversation('Explain quantum computing'), messages: [], updatedAt: Date.now() - 3_600_000 },
  { ...makeConversation('Refactor auth module'), messages: [], updatedAt: Date.now() - 86_400_000 },
]

export function useConversations() {
  const [conversations, setConversations] = useState<Conversation[]>(SEED_CONVERSATIONS)
  const [activeId, setActiveId] = useState<string | null>(null)

  const activeConversation = conversations.find((c) => c.id === activeId) ?? null

  const createConversation = useCallback(() => {
    const c = makeConversation()
    setConversations((prev) => [c, ...prev])
    setActiveId(c.id)
    return c
  }, [])

  const selectConversation = useCallback((id: string) => {
    setActiveId(id)
  }, [])

  const addMessage = useCallback((conversationId: string, message: Message) => {
    setConversations((prev) =>
      prev.map((c) =>
        c.id === conversationId
          ? {
              ...c,
              messages: [...c.messages, message],
              updatedAt: Date.now(),
              title: c.messages.length === 0 && message.role === 'user'
                ? message.content.slice(0, 48)
                : c.title,
            }
          : c
      )
    )
  }, [])

  const updateMessage = useCallback((conversationId: string, messageId: string, patch: Partial<Message>) => {
    setConversations((prev) =>
      prev.map((c) =>
        c.id === conversationId
          ? {
              ...c,
              messages: c.messages.map((m) =>
                m.id === messageId ? { ...m, ...patch } : m
              ),
            }
          : c
      )
    )
  }, [])

  const deleteConversation = useCallback((id: string) => {
    setConversations((prev) => prev.filter((c) => c.id !== id))
    setActiveId((prev) => (prev === id ? null : prev))
  }, [])

  return {
    conversations,
    activeId,
    activeConversation,
    createConversation,
    selectConversation,
    addMessage,
    updateMessage,
    deleteConversation,
  }
}
